pane-iceweasel-title = Iceweasel
category-iceweasel =
    .tooltiptext = 瀏覽器內部功能更改，易于訪問
iceweasel-header = Iceweasel 選項
iceweasel-warning-title = 注意！
iceweasel-warning-description = 我們仔細選擇默認設置，專注于隱私和安全。更改這些設置時，請閱讀描述以了解這些更改的影響。
iceweasel-extension-update-checkbox =
    .label = 自動更新附加組件
iceweasel-lastclose-checkbox =
    .label = 保留最后一個新分頁
iceweasel-tips-checkbox =
    .label = 允許分頁上的消息提示框
iceweasel-styling-checkbox =
    .label = 允許 userChrome.css 自定義
iceweasel-autocopy-checkbox =
    .label = 啟用中鍵粘貼
iceweasel-ipv6-checkbox =
    .label = 啟用 IPv6
iceweasel-javascript-checkbox =
    .label = 禁用 Javascript
iceweasel-libportable-heading = libportable 選項
iceweasel-libportable-upcheck-checkbox =
    .label = 啟用Iceweasel自動更新
iceweasel-libportable-ubo-checkbox =
    .label = 安裝 ublock origin
iceweasel-libportable-chrome-checkbox =
    .label = 啟用userChrome環境與鼠標手勢
iceweasel-libportable-bosskey-checkbox =
    .label = 啟用老板鍵
iceweasel-libportable-ontabs-checkbox =
    .label = 啟用分頁功能
iceweasel-hover-activate =
    .label = 鼠標懸停激活分頁
iceweasel-double-click-close =
    .label = 鼠標左鍵雙擊關閉分頁
iceweasel-double-click-new =
    .label = 鼠標左鍵雙擊標簽欄時新建分頁
iceweasel-mouse-hover-close =
    .label = 鼠標懸停在關閉按鈕時關閉分頁
iceweasel-mouse-hover-new =
    .label = 鼠標懸停在新建按鈕時新建分頁
iceweasel-right-click-close =
    .label = 鼠標右鍵單擊標簽時關閉分頁
iceweasel-right-click-recover =
    .label = 鼠標右鍵單擊標簽欄空白處時恢復分頁
iceweasel-extension-update-description = 無需手動干預即可保持擴展程序最新。這對您的安全很有利。
iceweasel-extension-update-warning1 = 如果您不在每次更新前審查擴展程序的代碼，應啟用此選項。
iceweasel-autocopy-description = 選擇一些文本復制，然后用鼠標中鍵粘貼。
iceweasel-ipv6-description = 允許 Iceweasel 使用 IPv6 連接。
iceweasel-ipv6-warning1 = 與其在瀏覽器中阻止 IPv6，我們建議在您的操作系統中啟用 IPv6 隱私擴展。
iceweasel-tips-description = 當禁用分頁預覽時，我們也禁用了分頁消息提示框。
iceweasel-tips-warning1 = 此選項可以恢復禁用分頁預覽后的消息提示框。
iceweasel-lastclose-description = 關閉最后一個分頁時不關閉瀏覽器。
iceweasel-lastclose-warning1 = 防止快速關閉分頁時錯誤的退出了瀏覽器。
iceweasel-styling-description = 如果要使用手動加載的主題自定義界面，請啟用此選項。
iceweasel-styling-warning1 = 確保您信任該主題的提供者。
iceweasel-javascript-description = JavaScript是大部分網頁的重要組成部分。
iceweasel-javascript-warning1 = 但有時候我們可能需要臨時禁用它，之后記得開啟哦。
iceweasel-libportable-description = libportable 庫額外提供的功能
iceweasel-libportable-warning1 = 即時生效需要Upcheck支持，不要刪除它。
iceweasel-libportable-upcheck-description = Upcheck隨瀏覽器啟動，24小時檢測一次，不會帶來額外消耗。
iceweasel-libportable-upcheck-warning1 = 如果出現提示更新失敗，你需要在下載目錄手動解壓包到安裝目錄。
iceweasel-libportable-ubo-description = 在瀏覽器中安裝 uBlock Origin 擴展。
iceweasel-libportable-ubo-warning1 = 需重啟。過濾規則越多，占用的內存也就越高。
iceweasel-libportable-chrome-description = 腳本文件會在后臺安裝到瀏覽器目錄，如果你原先存在userChrome環境，將不會安裝。<br>
                                           新的腳本文件支持Luajit，可以使用FFI調用系統原生API。
iceweasel-libportable-chrome-warning1 = 用戶腳本可能存在兼容性問題，請積極參與開源社區。如果你禁用此項，請先備份好你原先的腳本文件。
iceweasel-libportable-chrome-pop = userChrome環境安裝成功<br>重啟瀏覽器后生效
iceweasel-libportable-bosskey-description = 默認Ctrl+Shift+~，portable.ini 可修改快捷鍵。
iceweasel-libportable-bosskey-warning1 = 你需要防止快捷鍵與其他應用沖突。
iceweasel-libportable-ontabs-description = 對應 portable.ini 中的 OnTabs 選項。
iceweasel-libportable-ontabs-warning1 = Ontabs使用Automation技術對分頁進行操作。
iceweasel-footer = 有用的鏈接
iceweasel-config-link = 訪問 Iceweasel 項目
iceweasel-open-profile = 打開用戶配置文件目錄
iceweasel-restart-profile = 重啟瀏覽器