pane-iceweasel-title = Iceweasel
category-iceweasel =
    .tooltiptext = 浏览器内部功能更改，易于访问
iceweasel-header = Iceweasel 选项
iceweasel-warning-title = 注意！
iceweasel-warning-description = 我们仔细选择默认设置，专注于隐私和安全。更改这些设置时，请阅读描述以了解这些更改的影响。
iceweasel-extension-update-checkbox =
    .label = 自动更新附加组件
iceweasel-lastclose-checkbox =
    .label = 保留最后一个新标签页
iceweasel-tips-checkbox =
    .label = 允许标签页上的消息提示框
iceweasel-styling-checkbox =
    .label = 允许 userChrome.css 自定义
iceweasel-autocopy-checkbox =
    .label = 启用中键粘贴
iceweasel-ipv6-checkbox =
    .label = 启用 IPv6
iceweasel-javascript-checkbox =
    .label = 禁用 Javascript
iceweasel-libportable-heading = libportable 选项
iceweasel-libportable-upcheck-checkbox =
    .label = 启用Iceweasel自动更新
iceweasel-libportable-ubo-checkbox =
    .label = 安装 ublock origin
iceweasel-libportable-chrome-checkbox =
    .label = 启用userChrome环境与鼠标手势
iceweasel-libportable-bosskey-checkbox =
    .label = 启用老板键
iceweasel-libportable-ontabs-checkbox =
    .label = 启用标签页功能
iceweasel-hover-activate =
    .label = 鼠标悬停激活标签页
iceweasel-double-click-close =
    .label = 鼠标左键双击关闭标签页
iceweasel-double-click-new =
    .label = 鼠标左键双击标签栏时新建标签页
iceweasel-mouse-hover-close =
    .label = 鼠标悬停在关闭按钮时关闭标签页
iceweasel-mouse-hover-new =
    .label = 鼠标悬停在新建按钮时新建标签页
iceweasel-right-click-close =
    .label = 鼠标右键单击标签时关闭标签页
iceweasel-right-click-recover =
    .label = 鼠标右键单击标签栏空白处时恢复标签页
iceweasel-extension-update-description = 无需手动干预即可保持扩展程序最新。这对您的安全很有利。
iceweasel-extension-update-warning1 = 如果您不在每次更新前审查扩展程序的代码，应启用此选项。
iceweasel-autocopy-description = 选择一些文本复制，然后用鼠标中键粘贴。
iceweasel-ipv6-description = 允许 Iceweasel 使用 IPv6 连接。
iceweasel-ipv6-warning1 = 与其在浏览器中阻止 IPv6，我们建议在您的操作系统中启用 IPv6 隐私扩展。
iceweasel-tips-description = 当禁用标签页预览时，我们也禁用了标签页消息提示框。
iceweasel-tips-warning1 = 此选项可以恢复禁用标签页预览后的消息提示框。
iceweasel-lastclose-description = 关闭最后一个标签页时不关闭浏览器。
iceweasel-lastclose-warning1 = 防止快速关闭标签页时错误的退出了浏览器。
iceweasel-styling-description = 如果要使用手动加载的主题自定义界面，请启用此选项。
iceweasel-styling-warning1 = 确保您信任该主题的提供者。
iceweasel-javascript-description = JavaScript是大部分网页的重要组成部分。
iceweasel-javascript-warning1 = 但有时候我们可能需要临时禁用它，之后记得开启哦。
iceweasel-libportable-description = libportable 库额外提供的功能
iceweasel-libportable-warning1 = 即时生效需要Upcheck支持，不要删除它。
iceweasel-libportable-upcheck-description = Upcheck随浏览器启动，24小时检测一次，不会带来额外消耗。
iceweasel-libportable-upcheck-warning1 = 如果出现提示更新失败，你需要在下载目录手动解压包到安装目录。
iceweasel-libportable-ubo-description = 在浏览器中安装 uBlock Origin 扩展。
iceweasel-libportable-ubo-warning1 = 需重启。过滤规则越多，占用的内存也就越高。
iceweasel-libportable-chrome-description =
    脚本文件会在后台安装到浏览器目录，如果你原先存在userChrome环境，将不会安装。<br>
    新的脚本文件支持Luajit，可以使用FFI调用系统原生API。
iceweasel-libportable-chrome-warning1 = 用户脚本可能存在兼容性问题，请积极参与开源社区。如果你禁用此项，请先备份好你原先的脚本文件。
iceweasel-libportable-chrome-pop = userChrome环境安装成功<br>重启浏览器后生效
iceweasel-libportable-bosskey-description = 默认Ctrl+Shift+~，portable.ini 可修改快捷键。
iceweasel-libportable-bosskey-warning1 = 你需要防止快捷键与其他应用冲突。
iceweasel-libportable-ontabs-description = 对应 portable.ini 中的 OnTabs 选项。
iceweasel-libportable-ontabs-warning1 = Ontabs使用Automation技术对标签页进行操作。
iceweasel-footer = 有用的链接
iceweasel-config-link = 访问 Iceweasel 项目
iceweasel-open-profile = 打开用户配置文件目录
iceweasel-restart-profile = 重启浏览器
